//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZCustoms.Application.SGY.MessageService.UnitTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sgy.gzcustoms.gov.cn/Contracts", ConfigurationName="ServiceReference1.MessageServiceWCF")]
    public interface MessageServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/SendMessage", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/SendMessageResponse")]
        GZCustoms.Application.SGY.MessageService.Interface.MesReceipt SendMessage(string keyValue, string machineCode, string cusCiqNo, string msgXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/GetCusCiqNo", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/GetCusCiqNoResponse")]
        string GetCusCiqNo(string ieFlag, string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/DownloadCustomsData", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/DownloadCustomsDataRespon" +
            "se")]
        string DownloadCustomsData(string keyValue, string machineCode, string cusCiqNo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/DownloadCiqData", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/DownloadCiqDataResponse")]
        string DownloadCiqData(string keyValue, string machineCode, string cusCiqNo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UploadAllData", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UploadAllDataResponse")]
        GZCustoms.Application.SGY.MessageService.Interface.SaveModel UploadAllData(string keyValue, string machineCode, string ieFlag, string locationCode, string cusCiqNo, string cusMsgXml, string ciqMsgXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UploadCustomsData", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UploadCustomsDataResponse" +
            "")]
        GZCustoms.Application.SGY.MessageService.Interface.SaveModel UploadCustomsData(string keyValue, string machineCode, string ieFlag, string locationCode, string cusCiqNo, string msgXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/GetSaveTime", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/GetSaveTimeResponse")]
        System.DateTime GetSaveTime(string cusCiqNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/Login", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/LoginResponse")]
        GZCustoms.Application.SGY.MessageService.Interface.UserInfo Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UpdatePassword", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/UpdatePasswordResponse")]
        int UpdatePassword(string userName, string pwdOld, string pwdNew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ActiveKey", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ActiveKeyResponse")]
        int ActiveKey(string userGuid, string keyValue, string machineCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ActiveKeyByLoginName", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ActiveKeyByLoginNameRespo" +
            "nse")]
        int ActiveKeyByLoginName(string loginName, string password, string keyValue, string machineCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ReceiveMsgRep", ReplyAction="http://sgy.gzcustoms.gov.cn/Contracts/MessageServiceWCF/ReceiveMsgRepResponse")]
        GZCustoms.Application.SGY.MessageService.Interface.CusReturnInfo ReceiveMsgRep(string keyValue, string machineCode, string taskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceWCFChannel : GZCustoms.Application.SGY.MessageService.UnitTest.ServiceReference1.MessageServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceWCFClient : System.ServiceModel.ClientBase<GZCustoms.Application.SGY.MessageService.UnitTest.ServiceReference1.MessageServiceWCF>, GZCustoms.Application.SGY.MessageService.UnitTest.ServiceReference1.MessageServiceWCF {
        
        public MessageServiceWCFClient() {
        }
        
        public MessageServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GZCustoms.Application.SGY.MessageService.Interface.MesReceipt SendMessage(string keyValue, string machineCode, string cusCiqNo, string msgXml) {
            return base.Channel.SendMessage(keyValue, machineCode, cusCiqNo, msgXml);
        }
        
        public string GetCusCiqNo(string ieFlag, string locationCode) {
            return base.Channel.GetCusCiqNo(ieFlag, locationCode);
        }
        
        public string DownloadCustomsData(string keyValue, string machineCode, string cusCiqNo, string password) {
            return base.Channel.DownloadCustomsData(keyValue, machineCode, cusCiqNo, password);
        }
        
        public string DownloadCiqData(string keyValue, string machineCode, string cusCiqNo, string password) {
            return base.Channel.DownloadCiqData(keyValue, machineCode, cusCiqNo, password);
        }
        
        public GZCustoms.Application.SGY.MessageService.Interface.SaveModel UploadAllData(string keyValue, string machineCode, string ieFlag, string locationCode, string cusCiqNo, string cusMsgXml, string ciqMsgXml) {
            return base.Channel.UploadAllData(keyValue, machineCode, ieFlag, locationCode, cusCiqNo, cusMsgXml, ciqMsgXml);
        }
        
        public GZCustoms.Application.SGY.MessageService.Interface.SaveModel UploadCustomsData(string keyValue, string machineCode, string ieFlag, string locationCode, string cusCiqNo, string msgXml) {
            return base.Channel.UploadCustomsData(keyValue, machineCode, ieFlag, locationCode, cusCiqNo, msgXml);
        }
        
        public System.DateTime GetSaveTime(string cusCiqNo) {
            return base.Channel.GetSaveTime(cusCiqNo);
        }
        
        public GZCustoms.Application.SGY.MessageService.Interface.UserInfo Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public int UpdatePassword(string userName, string pwdOld, string pwdNew) {
            return base.Channel.UpdatePassword(userName, pwdOld, pwdNew);
        }
        
        public int ActiveKey(string userGuid, string keyValue, string machineCode) {
            return base.Channel.ActiveKey(userGuid, keyValue, machineCode);
        }
        
        public int ActiveKeyByLoginName(string loginName, string password, string keyValue, string machineCode) {
            return base.Channel.ActiveKeyByLoginName(loginName, password, keyValue, machineCode);
        }
        
        public GZCustoms.Application.SGY.MessageService.Interface.CusReturnInfo ReceiveMsgRep(string keyValue, string machineCode, string taskId) {
            return base.Channel.ReceiveMsgRep(keyValue, machineCode, taskId);
        }
    }
}
